{
 "title": "Chaos Experiments",
 "tags": [
  "chaos-demo",
  "chaos"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Experiments Created (1h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job, fault_type) (increase(chaos_experiment_total[1h]))"
    }
   ]
  },
  {
   "title": "Active Experiments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job, fault_type) (chaos_active_experiment)"
    }
   ]
  },
  {
   "title": "Experiment Success / Failure (1h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job, fault_type) (increase(chaos_experiment_success_total[1h]))"
    },
    {
     "expr": "sum by (job, fault_type) (increase(chaos_experiment_failed_total[1h]))"
    }
   ]
  },
  {
   "title": "Chaos Recovery P95 (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, job, fault_type) (rate(chaos_recovery_duration_seconds_bucket[10m])))"
    }
   ]
  }
 ]
}