{
 "title": "HTTP Overview",
 "tags": [
  "chaos-demo",
  "http"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Order QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_requests_total{route=\"/order\"}[1m]))"
    }
   ]
  },
  {
   "title": "P95 / P99 Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, job) (rate(http_request_duration_seconds_bucket{route=\"/order\"}[2m]))) * 1000"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, job) (rate(http_request_duration_seconds_bucket{route=\"/order\"}[2m]))) * 1000"
    }
   ]
  },
  {
   "title": "HTTP 5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_request_errors_total[1m])) / clamp_min(sum by (job) (rate(http_requests_total[1m])), 0.0001)"
    }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (http_requests_in_progress{route=\"/order\"})"
    }
   ]
  }
 ]
}